version: 2

# Build documentation with Sphinx (The RTD Native engine)
sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
